# Generated by Django 6.0 on 2026-01-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameswishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameslist',
            name='current_price',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameslist',
            name='discount',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameslist',
            name='discount_expiration',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameslist',
            name='final_price',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameslist',
            name='game_url',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameslist',
            name='is_included',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameslist',
            name='normal_price',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
    ]
