apiVersion: batch/v1
kind: CronJob
metadata:
  name: games-wishlist
spec:
  schedule: "15 0 * * *"
  timeZone: "Europe/Warsaw"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          initContainers:
            - name: ownership
              image: busybox:1.37.0
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: games-wishlist
                  mountPath: /games
              command:
                - /bin/sh
                - -c
                - "chown -R 1200:1201 /games && chmod -R 775 /games"
          containers:
            - name: job
              image: theadzik/games-whishlist-job:2025.12.31.3
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: games-wishlist
                  mountPath: /games
          restartPolicy: OnFailure
          volumes:
            - name: games-wishlist
              persistentVolumeClaim:
                claimName: games-wishlist-pvc
