apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wishlist-pvc
  namespace: wishlist
spec:
  storageClassName: "synology-nfs-retain"
  volumeName: wishlist-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
